version: '3.9'

services:
  youtube-backend:
    container_name: youtube-backend
    image: youtube-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8000'

  # db:
  #   image: mysql
  #   ports:
  #     - '8082:8000'
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root 
  #   volumes:
    