version: '3.9'

services:
  youtube-backend:
    container_name: youtube-backend
    image: youtube-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8001:8000'

  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
  
  adminer:
    container_name: adminer
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: galkaev
    restart: always
    ports:
      - "8080:8080"
  
  youtube-frontend:
    container_name: youtube-frontend
    image: youtube-frontend
    ports:
      - '80:80'
    # command: ["node", 'App.js']